export const BASE_STATS = {
  MaxHp:100, AttackTime:0.15, MaxAmmoCount:5, ReloadTime:1.5,
  ReloadSpeed:1, AttackSpeed:1, BulletDamage:5, BulletForce:10,
  MoveSpeedMultiplier:1, NumProjectiles:1, BulletSpread:30, ShotInaccuracy:5,
  BulletSpeed:440, BulletLifetime:0.72, Luck:1, CritChance:0.05,
  CritMultiplier:1.5, LowHealthDamageMultiplier:1, FullHealthDamageMultiplier:1,
  NumDashes:1, DashCooldown:3.8, DashInvulnTime:0.25, DashStrength:250,
  FireDamage:2.5, FireLifetime:5, FreezeLifetime:4, FreezeTimeScale:0.6,
  FreezeFireDamageMultiplier:1, FearLifetime:2, FearDamageMultiplier:1,
  CoinAttractRange:155, CoinAttractStrength:220, NumPerkChoices:3, PushStrength:200,
  LastAmmoDamageMultiplier:1, OverallDamageMultiplier:1, NonBulletDamageMultiplier:1,
  ExplosionSizeMultiplier:1, ExplosionDamageMultiplier:1, BulletDamageMultiplier:1,
  AttackSpeedStill:1, ReloadSpeedStill:1, ReloadingMovespeedMultiplier:1,
  ShootingMovespeedMultiplier:1, Friction:8.5, CameraDistance:800, RadiusMultiplier:1,
  XpGainMultiplier:1, HealthyUnitDamagePercent:1, Scale:1, PoisonDamage:1.2,
  TurnSpeed:10, HealEffectiveness:1, ShotDamageMult:1, HealthRegen:0,
  DodgeChance:0, DamageReductionPercent:0, BulletNumPiercing:0, BulletNumBouncing:0,
  BulletSplashChance:0, BulletSplashDamagePercent:0, BulletDamageGrow:0,
  ShootFireIgniteChance:0, ShootFreezeChance:0, ShootPoisonChance:0,
  FireSpreadChance:0, PoisonFinishDamagePercent:0, PoisonDieSpreadChance:0,
  RarityIncreaseCommon:0, RarityIncreaseUncommon:0, RarityIncreaseRare:0,
  RarityIncreaseEpic:0, RarityIncreaseMythic:0,
  RarityIncreaseLegendary:0, RarityIncreaseUnique:0, BossSpawnSecondsEarly:0,
  NumRerollsPerLevel:0, Kickback:0, BulletOverflowPercent:0,
  BulletDistanceDamage:0, BulletHomingRadiusDisplay:0, BulletHealTeammateAmount:0,
  BacksideDamageReductionPercent:0, FullHpDamageReductionPercent:0,
  SelfDmgReductionPercent:0, FearDamageReductionPercent:0,
  ExistingPerkChance:0, LevelUpExistingPerkChance:0,
  InvulnAfterHurtTimeDisplay:0, DashSlashBulletDamagePercent:0,
  HealthPackExtraHp:0, BackstabBonusDamagePercent:0,
  ArmorRerollCost:0, CoinHealAmount:0
};

export const RARITY_COLORS = {
  Common:'#9e9e9e', Uncommon:'#66bb6a', Rare:'#42a5f5', Epic:'#ab47bc',
  Mythic:'#ff7043', Legendary:'#ffd54f', Unique:'#ec407a'
};

export const RARITY_ORDER = ['Common','Uncommon','Rare','Epic','Mythic','Legendary','Unique'];

// Stats panel config - ordered to match the in-game STATS screen
export const STAT_DISPLAY = [
  // Combat - always shown
  { key:'_DPS', label:'DPS', icon:'📊', format:'1f', section:'COMBAT', alwaysShow:true },
  { key:'BulletDamage', label:'Bullet Damage', icon:'🔫', format:'1f', section:'COMBAT', alwaysShow:true },
  { key:'_DmgMult', label:'Damage Multiplier', icon:'⬆', format:'pctChange', section:'COMBAT', alwaysShow:true },
  { key:'NumProjectiles', label:'Bullets Per Shot', icon:'💠', format:'int', section:'COMBAT', alwaysShow:true },
  { key:'MaxAmmoCount', label:'Ammo', icon:'🎯', format:'int', section:'COMBAT', alwaysShow:true },
  { key:'AttackSpeed', label:'Attack Speed', icon:'⚡', format:'multPct', base:1, section:'COMBAT', alwaysShow:true },
  { key:'ReloadSpeed', label:'Reload Speed', icon:'🔄', format:'multPct', base:1, section:'COMBAT', alwaysShow:true },
  { key:'MoveSpeedMultiplier', label:'Move Speed', icon:'🏃', format:'multPct', base:1, section:'COMBAT', alwaysShow:true },
  // Survival
  { key:'MaxHp', label:'Max Health', icon:'❤', format:'intChange', base:100, section:'SURVIVAL', alwaysShow:true },
  { key:'HealthRegen', label:'Health Regen', icon:'💚', format:'perSec', section:'SURVIVAL' },
  { key:'DodgeChance', label:'Dodge Chance', icon:'🛡', format:'pct100', section:'SURVIVAL' },
  { key:'DamageReductionPercent', label:'Damage Reduction', icon:'🛡', format:'pct100', section:'SURVIVAL' },
  { key:'BacksideDamageReductionPercent', label:'Backside Dmg Reduction', icon:'🛡', format:'pct100', section:'SURVIVAL' },
  { key:'FullHpDamageReductionPercent', label:'Full HP Dmg Reduction', icon:'🛡', format:'pct100', section:'SURVIVAL' },
  { key:'SelfDmgReductionPercent', label:'Self Dmg Reduction', icon:'🛡', format:'pct100', section:'SURVIVAL' },
  { key:'HealEffectiveness', label:'Heal Effectiveness', icon:'💊', format:'multPct', base:1, section:'SURVIVAL' },
  { key:'InvulnAfterHurtTimeDisplay', label:'Invuln After Hurt', icon:'✨', format:'1f', section:'SURVIVAL' },
  // Bullet
  { key:'CritChance', label:'Bullet Crit Chance', icon:'💥', format:'pct100', section:'BULLET', alwaysShow:true },
  { key:'CritMultiplier', label:'Crit Multiplier', icon:'✖', format:'pct100', section:'BULLET', alwaysShow:true },
  { key:'BulletSplashChance', label:'Bullet Splash Chance', icon:'💦', format:'pct100', section:'BULLET' },
  { key:'BulletSplashDamagePercent', label:'Bullet Splash Damage', icon:'💦', format:'pct100', section:'BULLET' },
  { key:'BulletDamageGrow', label:'Bullet Damage Growth', icon:'📈', format:'perSec', section:'BULLET' },
  { key:'BulletDistanceDamage', label:'Distance Damage', icon:'📏', format:'1f', section:'BULLET' },
  { key:'BulletSpeed', label:'Bullet Speed', icon:'➡', format:'multPct', base:440, section:'BULLET' },
  { key:'BulletLifetime', label:'Bullet Lifetime', icon:'⏳', format:'2f', section:'BULLET' },
  { key:'BulletNumPiercing', label:'Bullet Pierce', icon:'🗡', format:'int', section:'BULLET' },
  { key:'BulletNumBouncing', label:'Bullet Bounces', icon:'↩', format:'int', section:'BULLET' },
  { key:'BulletOverflowPercent', label:'Bullet Overflow', icon:'💫', format:'pct100', section:'BULLET' },
  { key:'BulletHomingRadiusDisplay', label:'Homing Radius', icon:'🎯', format:'1f', section:'BULLET' },
  { key:'BulletHealTeammateAmount', label:'Heal Teammate', icon:'💚', format:'1f', section:'BULLET' },
  { key:'BulletForce', label:'Bullet Force', icon:'💪', format:'int', section:'BULLET' },
  { key:'Kickback', label:'Kickback', icon:'↩', format:'int', section:'BULLET' },
  { key:'BulletSpread', label:'Bullet Spread', icon:'📐', format:'int', section:'BULLET' },
  { key:'ShotInaccuracy', label:'Shot Inaccuracy', icon:'🎯', format:'int', section:'BULLET' },
  // Mobility
  { key:'NumDashes', label:'Num Dashes', icon:'💨', format:'int', section:'MOBILITY', alwaysShow:true },
  { key:'DashCooldown', label:'Dash Cooldown', icon:'⏱', format:'1f', section:'MOBILITY', inverted:true },
  { key:'DashStrength', label:'Dash Strength', icon:'💨', format:'int', section:'MOBILITY' },
  { key:'Scale', label:'Body Size', icon:'📐', format:'multPct', base:1, section:'MOBILITY' },
  { key:'CameraDistance', label:'Camera Distance', icon:'🔭', format:'multPct', base:800, section:'MOBILITY' },
  { key:'TurnSpeed', label:'Turn Speed', icon:'🔄', format:'1f', section:'MOBILITY' },
  // Elemental
  { key:'ShootFireIgniteChance', label:'Fire Chance', icon:'🔥', format:'pct100', section:'ELEMENTAL' },
  { key:'FireDamage', label:'Fire Damage', icon:'🔥', format:'1f', section:'ELEMENTAL' },
  { key:'FireLifetime', label:'Fire Duration', icon:'🔥', format:'1f', section:'ELEMENTAL' },
  { key:'FireSpreadChance', label:'Fire Spread', icon:'🔥', format:'pct100', section:'ELEMENTAL' },
  { key:'ShootFreezeChance', label:'Freeze Chance', icon:'❄', format:'pct100', section:'ELEMENTAL' },
  { key:'FreezeLifetime', label:'Freeze Duration', icon:'❄', format:'1f', section:'ELEMENTAL' },
  { key:'FreezeTimeScale', label:'Freeze Slow', icon:'❄', format:'multPct', base:0.6, section:'ELEMENTAL' },
  { key:'FreezeFireDamageMultiplier', label:'Freeze Fire Dmg', icon:'❄', format:'multPct', base:1, section:'ELEMENTAL' },
  { key:'ShootPoisonChance', label:'Poison Chance', icon:'☠', format:'pct100', section:'ELEMENTAL' },
  { key:'PoisonDamage', label:'Poison Damage', icon:'☠', format:'1f', section:'ELEMENTAL' },
  { key:'PoisonFinishDamagePercent', label:'Poison Finish Dmg', icon:'☠', format:'pct100', section:'ELEMENTAL' },
  { key:'PoisonDieSpreadChance', label:'Poison Spread', icon:'☠', format:'pct100', section:'ELEMENTAL' },
  { key:'FearLifetime', label:'Fear Duration', icon:'😱', format:'1f', section:'ELEMENTAL' },
  { key:'FearDamageMultiplier', label:'Fear Dmg Mult', icon:'😱', format:'multPct', base:1, section:'ELEMENTAL' },
  { key:'FearDamageReductionPercent', label:'Fear Dmg Reduction', icon:'😱', format:'pct100', section:'ELEMENTAL' },
  // Explosions & AoE
  { key:'ExplosionDamageMultiplier', label:'Explosion Damage', icon:'💣', format:'multPct', base:1, section:'EXPLOSIONS' },
  { key:'ExplosionSizeMultiplier', label:'Explosion Size', icon:'💣', format:'multPct', base:1, section:'EXPLOSIONS' },
  { key:'RadiusMultiplier', label:'AoE Radius', icon:'⭕', format:'multPct', base:1, section:'EXPLOSIONS' },
  { key:'DashSlashBulletDamagePercent', label:'Dash Slash Dmg', icon:'⚔', format:'pct100', section:'EXPLOSIONS' },
  // Misc
  { key:'NumPerkChoices', label:'Perk Choices', icon:'🃏', format:'int', section:'MISC' },
  { key:'NumRerollsPerLevel', label:'Rerolls/Level', icon:'🎲', format:'int', section:'MISC' },
  { key:'ExistingPerkChance', label:'Existing Perk Chance', icon:'🔁', format:'pct100', section:'MISC' },
  { key:'LevelUpExistingPerkChance', label:'Lvl-Up Existing Chance', icon:'🔁', format:'pct100', section:'MISC' },
  { key:'XpGainMultiplier', label:'XP Gain', icon:'⭐', format:'multPct', base:1, section:'MISC' },
  { key:'CoinAttractRange', label:'Item Attract Range', icon:'🧲', format:'multPct', base:155, section:'MISC' },
  { key:'PushStrength', label:'Push Strength', icon:'💪', format:'int', section:'MISC' },
  { key:'HealthPackExtraHp', label:'Healthpack Bonus HP', icon:'➕', format:'int', section:'MISC' },
  { key:'HealthyUnitDamagePercent', label:'Full HP Enemy Dmg', icon:'🎯', format:'multPct', base:1, section:'MISC' },
  { key:'BackstabBonusDamagePercent', label:'Backstab Dmg', icon:'🗡', format:'pct100', section:'MISC' },
  // Rarity
  { key:'RarityIncreaseCommon', label:'Common Perk Chance', icon:'⬜', format:'pctAdd', section:'RARITY' },
  { key:'RarityIncreaseUncommon', label:'Uncommon Perk Chance', icon:'🟩', format:'pctAdd', section:'RARITY' },
  { key:'RarityIncreaseRare', label:'Rare Perk Chance', icon:'🟦', format:'pctAdd', section:'RARITY' },
  { key:'RarityIncreaseEpic', label:'Epic Perk Chance', icon:'🟪', format:'pctAdd', section:'RARITY' },
  { key:'RarityIncreaseMythic', label:'Mythic Perk Chance', icon:'🟧', format:'pctAdd', section:'RARITY' },
  { key:'RarityIncreaseLegendary', label:'Legendary Perk Chance', icon:'⭐', format:'pctAdd', section:'RARITY' },
  { key:'RarityIncreaseUnique', label:'Unique Perk Chance', icon:'💎', format:'pctAdd', section:'RARITY' },
];

export const INVERTED_STATS = new Set(['DashCooldown','AttackTime','ReloadTime']);
